export default {
    addDataConnector: '[aria-label="Create Data Connector"]',
    nameInput: '#title',
    descriptionInput: '#description',
    authenticatonDropdown: '[aria-label="Authentication Type"]',
    authenticationTypeInput: '[name="authtype"]',
    authType: '//span[text()="AuthType"]',
    saveBtn: '//button[text()="Save"]',
    configurationtab: '(//li[@role="presentation"])[2]',
    tokenInput: '#token',
    addResource: '[aria-label="Create Resource"]',
    resourceDescription: '[name="description"]',
    resourceMethod: '[name="method"]',
    resourceURL: '[name="url"]',
    addBtn: '//button[text()="add"]',
    resourcestab: '(//li[@role="presentation"])[1]',
    resourceSendBtn:"//button[text()='Send']",
    configBtn:"(//a[@role='tab'])[2]",
    tokenTxtBx:'[id="token"]',
    resourcenavBtn:"(//a[@role='tab'])[1]",
    resourceNmeTxt:'[name="purpose"]',
    CategoryTxt: '[class="multiselect__tag"] span',
}